site_name: OCÉAN-SENTINELLE
site_description: Outil d’aide à la décision face à l’acidification du littoral en Nouvelle-Aquitaine
site_author: Alejandro Tomas Trujillo Castro
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest

nav:
  - Accueil: index.md
  - Utilisation:
      - Guide utilisateur: guide_utilisateur.md
      - Cas d’usage: cas_usage.md
  - Développement:
      - Architecture: architecture.md
      - Méthodologie: methodologie.md
      - Développeur: developpeur.md
      - Indicateurs: indicateurs.md
      - Configuration: config_README.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.superfences

docs_dir: docs
